package lab1;

import static org.junit.Assert.*;

import org.junit.Test;

public class NumeroTest {

	@Test
	public void test()  {
		String[] array = {"zero","um","dois","três","quatro","cinco","seis","sete","oito","nove","dez","onze","doze","treze","quatorze","quinze","dezesseis","dezessete","dezoito","dezenove"};
		Numero numero = new Numero();
		try{
			for (int i=0;i<20;i++){
				assertEquals(array[i],numero.transforma(i+""));
			} 
		} catch (Exception e){
			fail();
		}

		try{
			numero.transforma("");
			fail ("deveria ter lançado exceção!");
		} catch (Exception e){
			assertEquals("Número inválido", e.getMessage());
		}
		
		try{
			numero.transforma("ksdl");
			numero.transforma("xpto");
			fail ("tem que lançar exceção!");
		
		} catch (Exception e){
			
		}
		try{
			assertEquals("vinte e seis", numero.transforma("26"));
			assertEquals("cinquenta e nove", numero.transforma("59"));
		} catch (Exception e ){
			
		}


	}

}
